"""Stable error codes shared by the runtime worker and thin GUI client."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


RUNTIME_NOT_FOUND = "RUNTIME_NOT_FOUND"
PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
CONSENT_REQUIRED = "CONSENT_REQUIRED"
UNSUPPORTED_LANGUAGE = "UNSUPPORTED_LANGUAGE"
ENGINE_UNAVAILABLE = "ENGINE_UNAVAILABLE"
INVALID_REFERENCE = "INVALID_REFERENCE"
REFERENCE_DURATION_INVALID = "REFERENCE_DURATION_INVALID"
REFERENCE_VALIDATION_FAILED = "REFERENCE_VALIDATION_FAILED"
PROFILE_ID_CONFLICT = "PROFILE_ID_CONFLICT"
MODEL_LOAD_FAILED = "MODEL_LOAD_FAILED"
SYNTHESIS_FAILED = "SYNTHESIS_FAILED"
OUTPUT_VALIDATION_FAILED = "OUTPUT_VALIDATION_FAILED"
CANCELLED = "CANCELLED"
INVALID_REQUEST = "INVALID_REQUEST"
ALREADY_EXISTS = "ALREADY_EXISTS"
SOURCE_SEPARATION_FAILED = "SOURCE_SEPARATION_FAILED"
SOURCE_SEPARATION_NO_EFFECT = "SOURCE_SEPARATION_NO_EFFECT"
BACKGROUND_AUDIO_DETECTED = "BACKGROUND_AUDIO_DETECTED"
BACKGROUND_AUDIO_DETECTED_PENDING_LISTENING = (
    "BACKGROUND_AUDIO_DETECTED_PENDING_LISTENING"
)
NEEDS_MANUAL_REFERENCE = "NEEDS_MANUAL_REFERENCE"
REFERENCE_APPROVAL_REQUIRED = "REFERENCE_APPROVAL_REQUIRED"
PROFILE_REVISION_MISMATCH = "PROFILE_REVISION_MISMATCH"
REFERENCE_UPDATE_FAILED = "REFERENCE_UPDATE_FAILED"
XTTS_WORKER_LAUNCH_FAILED = "XTTS_WORKER_LAUNCH_FAILED"
XTTS_IMPORT_FAILED = "XTTS_IMPORT_FAILED"
XTTS_MODEL_NOT_FOUND = "XTTS_MODEL_NOT_FOUND"
XTTS_MODEL_LOAD_FAILED = "XTTS_MODEL_LOAD_FAILED"
XTTS_PROFILE_LOAD_FAILED = "XTTS_PROFILE_LOAD_FAILED"
XTTS_REFERENCE_INVALID = "XTTS_REFERENCE_INVALID"
XTTS_CONDITIONING_FAILED = "XTTS_CONDITIONING_FAILED"
XTTS_INFERENCE_FAILED = "XTTS_INFERENCE_FAILED"
XTTS_OUTPUT_WRITE_FAILED = "XTTS_OUTPUT_WRITE_FAILED"
XTTS_WORKER_CRASHED = "XTTS_WORKER_CRASHED"
XTTS_WORKER_TIMEOUT = "XTTS_WORKER_TIMEOUT"
XTTS_OUT_OF_MEMORY = "XTTS_OUT_OF_MEMORY"
DUPLICATE_JOB_REJECTED = "DUPLICATE_JOB_REJECTED"


@dataclass(slots=True)
class VoiceRuntimeError(Exception):
    code: str
    message: str
    details: dict[str, Any] = field(default_factory=dict)

    def __str__(self) -> str:
        return self.message

    def as_dict(self) -> dict[str, Any]:
        return {
            "type": "error",
            "code": self.code,
            "message": self.message,
            "details": self.details,
        }
